name: odroe
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.0

environment:
  sdk: ^3.4.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.5.0
  path: ^1.9.0
  spry: ^5.0.2
  analyzer: ^6.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
