name: odroe
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.0-297.0.dev

dependencies:
  macros: ^0.1.0-main.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
