name: odroe
description: A declarative, efficient, and flexible Flutter UI framework for building user interfaces.
version: 0.0.7
homepage: https://odroe.dev
repository: https://github.com/odroe/odroe
funding:
  - https://github.com/sponsors/medz
  - https://github.com/sponsors/odroe
  - https://opencollective.com/openodroe

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
