name: odroe
description: A declarative, efficient, and flexible Flutter UI framework for building user interfaces.
version: 0.0.8
homepage: https://odroe.dev
repository: https://github.com/odroe/odroe
funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe

environment:
  sdk: ^3.4.3
  flutter: ^3.22.2

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.24.9
